name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt install automake autoconf libtool texinfo texi2html gcc ruby make
      - name: build
        run: ./build-gcc/build-aptex.sh
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: build macOS binaries
        run: ./build-gcc/build-aptex.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aptex-macOS-lastest.tar
          path: |
            ./src/ptex-ng
            ./src/lsotfea
